name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to VPS
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
        run: |
          # Install required dependencies
          sudo apt-get update
          sudo apt-get install -y sshpass

          # Deploy to VPS
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USER@$HOST "
            cd $PROJECT_DIR &&
            git pull origin main &&
            npm install &&
            pm2 restart formasi-api
          "
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Install the required dependency
          sudo apt-get update
          sudo apt-get install -y curl

          # Send a notification to Discord
          curl -X POST -H "Content-Type: application/json" --data "{\"content\":\"Application has been deployed to the VPS\"}" "$DISCORD_WEBHOOK"
